-- =====================================================================
--  Joyería ARIGA - Actualización 06
--  * Rango de códigos de cliente por usuario: cada vendedor numera a sus
--    clientes en orden dentro de su rango (ej. Pablo 1-5000, Carlos
--    5001-10000).
--  * Usuarios sin rango usan la numeración general, que salta los rangos
--    asignados.
--
--  Ejecutar en Supabase > SQL Editor DESPUÉS de 05_inteligencia_y_traslados.sql.
--  Se puede ejecutar varias veces. No cambia los códigos ya existentes.
-- =====================================================================

-- Rango de códigos del usuario (ambos o ninguno)
alter table tiendaariga.perfiles add column if not exists rango_desde bigint;
alter table tiendaariga.perfiles add column if not exists rango_hasta bigint;
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'perfiles_rango_ck') then
    alter table tiendaariga.perfiles add constraint perfiles_rango_ck check (
      (rango_desde is null and rango_hasta is null)
      or (rango_desde >= 1 and rango_hasta >= rango_desde));
  end if;
end $$;

-- Dos usuarios no pueden tener rangos que se crucen
create or replace function tiendaariga.validar_rango_usuario()
returns trigger
language plpgsql
security definer
set search_path = tiendaariga
as $$
declare otro perfiles;
begin
  if new.rango_desde is null then return new; end if;
  select * into otro from perfiles
   where id <> new.id and rango_desde is not null
     and new.rango_desde <= rango_hasta and rango_desde <= new.rango_hasta
   limit 1;
  if found then
    raise exception 'El rango %-% se cruza con el de % (%-%)',
      new.rango_desde, new.rango_hasta, coalesce(otro.nombre, otro.usuario), otro.rango_desde, otro.rango_hasta;
  end if;
  return new;
end;
$$;
drop trigger if exists perfiles_validar_rango on tiendaariga.perfiles;
create trigger perfiles_validar_rango
  before insert or update of rango_desde, rango_hasta on tiendaariga.perfiles
  for each row execute function tiendaariga.validar_rango_usuario();

-- El código del cliente (clientes.id) lo asigna la base al crear el cliente
alter table tiendaariga.clientes alter column id set generated by default;

-- Siguiente código para un usuario (sin reservarlo). null si su rango está lleno.
create or replace function tiendaariga.calcular_codigo_cliente(p_usuario uuid)
returns bigint
language plpgsql
security definer
set search_path = tiendaariga
as $$
declare
  r perfiles;
  v bigint;
  h bigint;
begin
  select * into r from perfiles where id = p_usuario;
  if r.rango_desde is not null then
    -- En orden dentro del rango: después del código más alto ya usado en él
    select coalesce(max(id), r.rango_desde - 1) + 1 into v
      from clientes where id between r.rango_desde and r.rango_hasta;
    return case when v > r.rango_hasta then null else v end;
  end if;
  -- Numeración general: después del código más alto que no es de ningún
  -- rango, saltando los rangos asignados y los códigos ya usados
  select coalesce(max(c.id), 0) + 1 into v
    from clientes c
   where not exists (select 1 from perfiles p
                     where p.rango_desde is not null and c.id between p.rango_desde and p.rango_hasta);
  loop
    select rango_hasta into h from perfiles
     where rango_desde is not null and v between rango_desde and rango_hasta;
    if found then v := h + 1; continue; end if;
    exit when not exists (select 1 from clientes where id = v);
    v := v + 1;
  end loop;
  return v;
end;
$$;

create or replace function tiendaariga.asignar_codigo_cliente()
returns trigger
language plpgsql
security definer
set search_path = tiendaariga
as $$
declare v bigint;
begin
  -- Un código a la vez, para que dos altas simultáneas no tomen el mismo
  perform pg_advisory_xact_lock(hashtext('tiendaariga.codigo_cliente'));
  v := calcular_codigo_cliente(auth.uid());
  if v is null then
    raise exception 'Se acabó su rango de códigos de cliente. Pida al administrador que le amplíe el rango.';
  end if;
  new.id := v;
  return new;
end;
$$;
drop trigger if exists clientes_asignar_codigo on tiendaariga.clientes;
create trigger clientes_asignar_codigo
  before insert on tiendaariga.clientes
  for each row execute function tiendaariga.asignar_codigo_cliente();

-- Para la ficha del cliente: "próximo código"
create or replace function tiendaariga.proximo_codigo_cliente()
returns bigint
language sql stable
security definer
set search_path = tiendaariga
as $$
  select case when usuario_activo() then calcular_codigo_cliente(auth.uid()) end
$$;

-- Para la pestaña Usuarios (solo administradores): uso de cada rango
create or replace function tiendaariga.uso_rangos_clientes()
returns table (perfil_id uuid, usados bigint, proximo bigint)
language sql stable
security definer
set search_path = tiendaariga
as $$
  select p.id,
         (select count(*) from clientes c where c.id between p.rango_desde and p.rango_hasta),
         calcular_codigo_cliente(p.id)
  from perfiles p
  where p.rango_desde is not null and es_admin()
$$;

revoke execute on function tiendaariga.calcular_codigo_cliente(uuid) from public, anon, authenticated;
revoke execute on function tiendaariga.asignar_codigo_cliente()      from public, anon, authenticated;
revoke execute on function tiendaariga.validar_rango_usuario()       from public, anon, authenticated;
revoke execute on function tiendaariga.proximo_codigo_cliente()      from public, anon;
revoke execute on function tiendaariga.uso_rangos_clientes()         from public, anon;
grant  execute on function tiendaariga.proximo_codigo_cliente()      to authenticated;
grant  execute on function tiendaariga.uso_rangos_clientes()         to authenticated;

notify pgrst, 'reload schema';
